apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - rbac.yaml
  - sandbox-gcs-sa.yaml
  - postgres-secret.yaml
  - postgres.yaml
  - admin-secret.yaml

# Default namespace
namespace: default
